name: "Indeo upack setup"
description: "Install latest version of upack binary."
inputs:
  github_token:
    description: 'Github token'
    required: true
outputs:
  upack-path:
    description: "Path to the upack binary"
branding:
  icon: "package"
  color: "gray-dark"
runs:
  using: "node16"
  main: "lib/index.js"
